server {
    listen 80;

    # Serve React frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Forward API requests to Django
    location /api/ {
        proxy_pass         http://backend:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # Forward admin requests to Django
    location /admin/ {
        proxy_pass         http://backend:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # Serve Django static files (fixes admin CSS)
    location /static/ {
        proxy_pass         http://backend:8000;
        proxy_set_header   Host $host;
    }

    # Serve Django media files
    location /media/ {
        proxy_pass         http://backend:8000;
        proxy_set_header   Host $host;
    }
}
